// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  { name: "Custom AI Solutions", price: "From $2,000+", description: "Cutting-edge AI automation, chatbots, and machine learning solutions tailored to streamline your business operations." },
  { name: "Professional Writing / Ghostwriting", price: "From $500+", description: "Expert ghostwriting for LinkedIn, blogs, ebooks, and website copy that captures your authentic voice." },
  { name: "Website Development", price: "From $1,500+", description: "Custom website design, development, maintenance, and updates." },
  { name: "Facebook Ads", price: "From $800+/mo", description: "Strategic Facebook advertising campaigns, audience targeting, and performance optimization." },
  { name: "Virtual Assistance", price: "Contact for pricing", description: "Executive-level VA support for busy founders and teams." },
  { name: "Email Marketing", price: "Contact for pricing", description: "Newsletter strategy, automation, and campaign management." },
  { name: "Chatbot Automation", price: "Contact for pricing", description: "Conversational AI bots for support and lead capture." },
  { name: "Technical Writing", price: "Contact for pricing", description: "Documentation, whitepapers, and technical content." },
  { name: "Social Media Marketing", price: "Contact for pricing", description: "Content, scheduling, and growth strategy across platforms." }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List WriterSure services",
  description: "Returns the full list of services WriterSure offers, with pricing where available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  brand: "WriterSure",
  lead: "Alex Alney (Uday)",
  bookingUrl: "https://calendly.com/writersure369/30min",
  primaryCTA: "Book Free Strategy Call",
  website: "https://www.writersure.com",
  channels: ["Email", "Phone", "WhatsApp", "X"]
};
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Returns WriterSure contact channels and the free strategy call booking link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var faqs = [
  { q: "What services does WriterSure offer?", a: "AI-powered content and digital services: ghostwriting, virtual assistance, email marketing, chatbot automation, coding, technical writing, freelance writing, website design, AI generalist solutions, and social media marketing." },
  { q: "How does your AI-powered content creation process work?", a: "AI generates drafts; expert humans review, edit, and refine for brand voice and quality." },
  { q: "Do you offer customized solutions for specific industries?", a: "Yes \u2014 tech, healthcare, finance, education, e-commerce, and more." },
  { q: "How do you ensure quality and originality?", a: "Multiple rounds of editing, fact-checking, plagiarism detection, and specialist review." },
  { q: "Typical turnaround time?", a: "3\u20135 business days for standard content; complex projects get a detailed timeline in consultation." },
  { q: "Do you offer ongoing support?", a: "Yes, customizable ongoing support and maintenance packages." },
  { q: "How is pricing structured?", a: "Project-based, retainer, or subscription \u2014 quoted after an initial consultation." },
  { q: "Can you help implement AI into my existing business processes?", a: "Yes, our AI generalist solutions integrate with existing workflows." }
];
var list_faqs_default = defineTool3({
  name: "list_faqs",
  title: "List FAQs",
  description: "Returns WriterSure's frequently asked questions and answers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(faqs, null, 2) }],
    structuredContent: { faqs }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "writersure-mcp",
  title: "WriterSure MCP",
  version: "0.1.0",
  instructions: "Public tools for the WriterSure marketing site. Use list_services to see offerings and pricing, get_contact_info for the strategy-call booking link and contact channels, and list_faqs for common questions.",
  tools: [list_services_default, get_contact_info_default, list_faqs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
